services:
  rabbitmq:
    image: rabbitmq:3.9.29-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    container_name: 'rabbitmqp'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
