server:
  port: 8081

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbit-config:
  queue: rabbit-queue
  exchange: direct-exchange
  routing-key: direct-routing-key
